### ISSUE TITLE
Installation on Ubuntu

### ISSUE THREAD

**Issue by tec** [tfeldmann/Raumfeld-Desktop#2]
Thanks a lot for providing these scripts :-)

I just tested them using Ubuntu 14.04. Following you installation instructions did not just work for me. raumfeld required pysimplesoap and PySide had some reqirements, too. These steps here did succeed, maybe you want to include them in your installation description:

```
sudo apt-get install python3 python3-pip python3-pyside pyside-tools
sudo apt-get install qt4-qmake qt4-dev-tools

sudo pip3 install -U pysimplesoap
sudo pip3 install -U raumfeld
sudo pip3 install -U PySide
```

**Comment by tfeldmann** [comment]
Thank you very much for your input. Normally pip and apt handle the dependencies well (pysimplesoap) -- I will look into that.

**Comment by tfeldmann** [comment]
There was a bug in the python-raumfeld packaging process. It worked for me, but failed to install pysimplesoap for everyone else. It is now fixed, thanks for reporting!
