### ISSUE TITLE
Raumfeld Connector is found, but controls do not work

### ISSUE THREAD

**Issue by nagelp** [tfeldmann/Raumfeld-Desktop#4]
Thanks for working on this! I'd love to control my Teufel / Raumfeld Connector from my Linux machine.

I've just tried it out, but did not get very far. Here is what I did:

- Cloned this repo, commit c23f57afec562a117315b94b202263e9964e7910
- Installed dependencies via apt-get, because "pip3 install -Ur requirements.txt" failed with the following error message:

> ~/git/Raumfeld-Desktop$ pip3 install -Ur requirements.txt
> Collecting raumfeld (from -r requirements.txt (line 1))
>   Downloading raumfeld-0.2.tar.gz
> Collecting PySide (from -r requirements.txt (line 2))
>   Downloading PySide-1.2.4.tar.gz (9.3MB)
>     100% |████████████████████████████████| 9.3MB 137kB/s 
>     Complete output from command python setup.py egg_info:
>     only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ij85m73l/PySide/

- Built via "python3 build.py"
- Ran via "python3 main.py" and got the following output:

> ~/git/Raumfeld-Desktop$ python3 main.py
> http://192.168.1.106:60803/03f213b0-94ae-492e-b65b-88db5903f7a1.xml
> b'<?xml version="1.0"?><s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body><u:GetMuteResponse xmlns:u=urn:upnp-org:serviceId:RenderingControl"><CurrentMute>0</CurrentMute></u:GetMuteResponse></s:Body></s:Envelope>'
> Traceback (most recent call last):
>   File "/home/pn/git/Raumfeld-Desktop/raumfeld_desktop/mainwindow.py", line 43, in run
>     self.volume_infos.emit(self.device.mute, self.device.volume)
>   File "/home/pn/.local/lib/python3.6/site-packages/raumfeld/__init__.py", line 117, in mute
>     response = self.rendering_control.GetMute(InstanceID=1, Channel=1)
>   File "/home/pn/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 175, in <lambda>
>     return lambda *args, **kwargs: self.call(attr, *args, **kwargs)
>   File "/home/pn/.local/lib/python3.6/site-packages/pysimplesoap/client.py", line 258, in call
>     jetty=self.__soap_server in ('jetty',))
>   File "/home/pn/.local/lib/python3.6/site-packages/pysimplesoap/simplexml.py", line 56, in __init__
>     self.__document = xml.dom.minidom.parseString(text)
>   File "/usr/lib/python3.6/xml/dom/minidom.py", line 1968, in parseString
>     return expatbuilder.parseString(string)
>   File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 925, in parseString
>     return builder.parseString(string)
>   File "/usr/lib/python3.6/xml/dom/expatbuilder.py", line 223, in parseString
>     parser.Parse(string, True)
> xml.parsers.expat.ExpatError: not well-formed (invalid token): line 1, column 180

The window opened up, and after a few seconds, the name of my Raumfeld Connector showed at the bottom of the window. But when I press the Mute button, or move any of the two sliders, nothing happens at all.

Let me know how I can help :)

Linux distro: Kubuntu 17.10
My Raumfeld Connector says (under Chromecast built-in Information, not sure whether it's relevant): Version 1.21.75965

**Comment by tfeldmann** [comment]
Hi! Thank you for the detailed report. This could be a bug in the SOAP lib - see https://github.com/maierp/PyRaumfeld/issues/6 and the fix in https://github.com/pysimplesoap/pysimplesoap/pull/161
So maybe updating the pysimplesoap lib could fix this.
I'm working on the installation issues 👍
